# Generated by Django 5.2.8 on 2025-11-13 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('gmail', 'Gmail'), ('discord', 'Discord'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp Business'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('account_identifier', models.CharField(help_text='Email, username, or account ID', max_length=255)),
                ('encrypted_token', models.TextField(help_text='Encrypted OAuth token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('owner', 'service_name', 'account_identifier')},
            },
        ),
    ]
