# Generated by Django 5.2.8 on 2025-11-13 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_message_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('action_type', models.CharField(choices=[('send_notification', 'Send Notification'), ('save_message', 'Save Message'), ('send_email', 'Send Email'), ('trigger_task', 'Trigger Another Task'), ('upload_content', 'Upload Content'), ('forward_message', 'Forward Message'), ('create_task', 'Create Task'), ('summarize_text', 'Summarize Text')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_config', models.BooleanField(default=False, help_text='Whether this action requires additional configuration')),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for action configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Configuration used for this execution')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Result data from execution')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='actions.action')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('triggering_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
