# Generated by Django 5.2.8 on 2025-11-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_rename_name_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the message content'),
        ),
    ]
