# Generated by Django 5.2.8 on 2025-11-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('actions', '0001_initial'),
        ('messages_app', '0001_initial'),
        ('tasks', '0003_message_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='task',
            name='settings',
        ),
        migrations.AddField(
            model_name='task',
            name='ai_config',
            field=models.JSONField(blank=True, default=dict, help_text='AI processing configuration'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_count',
            field=models.IntegerField(default=0, help_text='Number of times this task has executed'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this task is actively monitoring'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='linked_accounts',
            field=models.ManyToManyField(blank=True, related_name='monitoring_tasks', to='accounts.linkedaccount'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_executions',
            field=models.IntegerField(default=0, help_text='Max executions (0 = unlimited)'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='actions',
        ),
        migrations.AlterField(
            model_name='task',
            name='prompt',
            field=models.TextField(help_text='AI prompt describing when and how this task should execute'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_decision', models.JSONField(blank=True, default=dict, help_text='AI decision and reasoning')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('actions_executed', models.ManyToManyField(blank=True, to='actions.actionexecution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tasks.task')),
                ('triggering_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messages_app.message')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='task',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='actions.action'),
        ),
    ]
