# Generated by Django 5.2.8 on 2025-11-13 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary', null=True)),
                ('external_message_id', models.CharField(blank=True, help_text='ID from the source platform', max_length=255)),
                ('sender_info', models.JSONField(blank=True, default=dict, help_text='Information about the sender')),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed Processing')], default='unprocessed', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis results')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.linkedaccount')),
                ('triggered_actions', models.ManyToManyField(blank=True, related_name='triggering_messages', to='actions.actionexecution')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_account', 'external_message_id')},
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_thread_id', models.CharField(blank=True, help_text='Thread ID from source platform', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('messages', models.ManyToManyField(related_name='threads', to='messages_app.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='accounts.linkedaccount')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('source_account', 'external_thread_id')},
            },
        ),
    ]
